image: continuumio/miniconda3

stages:
 - test


# execute the segmentation prediction with a test image
test-online-exec:
  variables:
    SERVICE_LOG_NAME: "/builds/service-logs/logs-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}.txt"
    FF_NETWORK_PER_BUILD: "true"     # activate container-to-container networking
  stage: test
  tags:
    - big-ram
  services:
    - name: $CI_REGISTRY/satomi/seg-serve/server:master
      alias: segserve
      command:
      - /bin/bash
      - -c
      - "echo $USER; echo Log dir: ${SERVICE_LOG_NAME}; ls /; ls -all /builds; mkdir -p /builds/service-logs; ls /builds; uvicorn --host 0.0.0.0 --port 80 main:app 2>&1 | tee ${SERVICE_LOG_NAME}"

  script:
    - echo "Log dir ${SERVICE_LOG_NAME}"
    - |
      (tail -f -n +1 "${SERVICE_LOG_NAME}" | awk '{print "[service-logs]: " $0}' &)
    - pip install requests pillow coverage mlflow
    - python -m unittest tests/test_online.py
    - python -m coverage run --source=./ -m unittest tests/test.py
    - coverage xml
  after_script:
    - rm ${SERVICE_LOG_NAME}
  artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml

test-local:
  stage: test
  script:
    - pip install requests pillow coverage mlflow
    - python -m unittest tests/test_local.py
    - python -m coverage run --source=./ -m unittest tests/test.py
    - coverage xml
  artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml

